{% set version = "7.76.1" %}

package:
  name: chaquopy-curl-openssl-3
  version: {{ version }}

source:
  url: https://curl.se/download/curl-{{ version }}.tar.gz

build:
  number: 1

requirements:
  host:
    - openssl
