package:
  name: igraph
  version: "0.11.5"


build:
  number: 0
  script_env:
    # parallelize compilation
    - MAKEFLAGS=-j${CPU_COUNT}
    - IGRAPH_CMAKE_EXTRA_ARGS=-DF2C_EXTERNAL_ARITH_HEADER=../../../../../../../android64_x86_64_arm64.h -DIEEE754_DOUBLE_ENDIANNESS_MATCHES=ON

