{% set version = "1.1.0" %}

package:
  name: torch
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: v{{ version }}

requirements:
  build:
    - cmake
  host:
    - python
    - chaquopy-libgfortran 4.9.3  # arm64-v8a uses ld.bfd, which transitively resolves all symbols.
    - chaquopy-openblas 0.2.20
    - numpy 1.17.4
