{% set version = "1.4.0" %}

package:
  name: torch
  version: {{ version }}

source:
  git_url: https://github.com/pytorch/pytorch.git
  git_rev: v{{ version }}

requirements:
  build:
    - cmake
  host:
    - python
    - numpy 1.17.4
