package:
  name: scipy
  version: 1.4.1

requirements:
  build:
    # setup.py has pybind11 in setup_requires, but this doesn't work because the headers aren't
    # unpacked correctly (https://github.com/pybind/python_example/issues/16).
    - pybind11 2.4.3
  host:
    - chaquopy-libgfortran 4.9
    - chaquopy-openblas 0.2.20
    - numpy 1.23.3

# to build scipy package a Fortran compiler is needed in the toolchain
# you can grab the ones found here from legacy NDK 21e:
# https://github.com/mzakharo/android-gfortran/releases/tag/r21e
# and use your OS `update-alternatives` or equivalent command 
# to temporarly override your `gfortran` with them
