package:
  name: scipy
  version: "1.8.1"

requirements:
  build:
    - fortran
    - cython 0.29.36        
  host:
    - chaquopy-libgfortran 4.9
    - chaquopy-openblas 0.2.20
    - numpy 1.20.3    
