{% set version = "1.13.1" %}

package:
  name: tensorflow
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz

requirements:

  # See https://www.tensorflow.org/install/source.
  build:
    - numpy 1.16.2
    - keras_applications 1.0.6      # Version numbers from tensorflow/tools/pip_package/setup.py
    - keras_preprocessing 1.0.5     #

  host:
    - python
    - numpy 1.16.2
