package:
  name: tensorflow
  version: 1.10.1

build:
  number: 8

source:
  url: https://github.com/tensorflow/tensorflow/archive/v1.10.1.tar.gz

requirements:
  # Everything is built for the host machine too: see README.md.
  build:
    - numpy 1.15.4
  host:
    - python
    - numpy 1.15.4
