{% set version = "1.16.1" %}

package:
  name: lsl
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/sccn/liblsl/releases/download/v{{ version }}/liblsl-{{ version }}-OSX_amd64.tar.bz2

requirements:
  build:
    - cmake