{% set version = "1.16.1" %}

package:
  name: lsl
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/sccn/liblsl.git
  git_rev: v{{ version }}

requirements:
  build:
    - cmake