{% set version = "1.3.7" %}

package:
  name: chaquopy-libvorbis
  version: {{ version }}

source:
  url: https://downloads.xiph.org/releases/vorbis/libvorbis-{{ version }}.tar.gz

requirements:
  host:
    - chaquopy-libogg 1.3.4
