package:
  name: lameenc
  # When updating, consider updating chaquopy-lame as well.
  version: 1.4.2

source:
  git_url: https://github.com/chrisstaite/lameenc
  git_rev: b2efb862552585857be0947f3beaff54290dbe19

requirements:
  build:
    - packaging 22.0
  host:
    - chaquopy-liblame 3.100
    - python
