# The OpenCV releases on PyPI come from the unofficial skvark repository. Each release is
# tagged with a sequence number, which is appended to the underlying OpenCV version to
# form a 4-component version number on PyPI.

package:
  name: opencv-python
  version: 3.4.2.16

source:
  # sdists are not currently available (https://github.com/skvark/opencv-python/issues/43), and
  # we can't use the GitHub-generated archive files because they don't contain submodules.
  git_url: https://github.com/skvark/opencv-python.git
  git_rev: 16

build:
  number: 3

requirements:
  build:
    - cmake
    - scikit-build 0.7.1
  host:
    - chaquopy-libpng 1.6.34
    - chaquopy-libjpeg 1.5.3
    - numpy 1.15.4
    - python
