{% if PY_VER == "3.8" %}
    {% set numpy_version = "1.19.5" %}
{% else %}
    {% set numpy_version = "1.23.3" %}
{% endif %}

package:
  name: scikit-learn
  version: "1.1.3"

requirements:
  build:
    - cython 0.29.24
  host:
    - chaquopy-openblas 0.2.20
    - numpy {{ numpy_version }}
    - scipy 1.4.1
