名称:CI
打开:
推:
分支:[Master]

并发:
集团:${{Github.ref}}
取消-进行中:真的

默认值:
运行:
壳牌:巴什

工作岗位:

产品:
Runs-on:Ubuntu-20.04
步骤:
-用途:斯莫里莫托/tune-github-hosted-runner-network@v1.0.0
-用途:操作/checkout@v4.1.6

-用途:./.github/actions/setup-python
ID:设置-Python

      #此步骤引用自product/readme.md。
-名称:下载Android Python版本
运行:|
CD目标
对于$(./list-versitions.py--build)中的版本；执行
Target_dir=../maven/com/chaquo/python/target/$version
./download-target.sh$target_dir
./unpackage-target.sh$TARGET_DIR前缀
完成

-名称:安装Python要求
运行:|
          ${{ steps.setup-python.outputs.python-default }} -m \
              pip install -r product/runtime/requirements-build.txt

      - uses: ./.github/actions/create-local-properties

      - name: Build
        run: |
          cd product
          export JAVA_HOME=$JAVA_HOME_11_X64
          ./gradlew publish -P cmakeBuildType=Release

      - name: Upload Maven repository
        uses: actions/upload-artifact@v4.3.3
        with:
          name: maven
          # There's a fairly large per-file overhead, so exclude the hash files.
          path: |
            maven
            !**/*.md5
            !**/*.sha1
            !**/*.sha256
            !**/*.sha512
          if-no-files-found: error

      # This should match the version discovery logic in gradle-plugin/build.gradle.kts.
      - name: List Android Gradle plugin versions
        id: agp-versions
        run: |
          cd product/gradle-plugin/src/test/integration/data/base
          (
              echo -n versions=
              echo *.* | jq -cR 'split(" ")'
          ) >> $GITHUB_OUTPUT

    outputs:
      agp-versions: ${{ steps.agp-versions.outputs.versions }}


  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: smorimoto/tune-github-hosted-runner-network@v1.0.0
      - uses: actions/checkout@v4.1.6

      - uses: ./.github/actions/setup-python
        id: setup-python

      - name: Install Python requirements
        run: |
          ${{ steps.setup-python.outputs.python-default }} -m \
              pip install -r product/runtime/requirements-build.txt \
                          -r product/runtime/requirements-docs.txt

      - uses: ./.github/actions/create-local-properties

      - name: Build
        run: |
          cd product
          export JAVA_HOME=$JAVA_HOME_11_X64
          ./gradlew docs

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: docs
          path: |
            product/runtime/build/docs
            !**/.doctrees
          if-no-files-found: error


  gradlePython:
    runs-on: ubuntu-20.04
    steps:
      - uses: smorimoto/tune-github-hosted-runner-network@v1.0.0
      - uses: actions/checkout@v4.1.6

      - uses: ./.github/actions/setup-python

      - uses: ./.github/actions/create-local-properties

      - name: Test
        run: |
          cd product
          export JAVA_HOME=$JAVA_HOME_11_X64
          ./gradlew gradle:testPython


  demo:
    needs: [product]
    runs-on: ubuntu-20.04
    steps:
      - uses: smorimoto/tune-github-hosted-runner-network@v1.0.0
      - uses: actions/checkout@v4.1.6

      - uses: ./.github/actions/setup-python

      - name: Download Maven repository
        uses: actions/download-artifact@v4.1.7
        with:
          name: maven
          path: maven

      - name: Get keystore
        env:
          CHAQUO_JKS: ${{ secrets.CHAQUO_JKS }}
        run: |
          echo "$CHAQUO_JKS" | base64 -d > demo/chaquo.jks

      - name: Build
        run: |
          cd demo
          export JAVA_HOME=$JAVA_HOME_17_X64
          ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: demo
          path: demo/app/build/outputs/apk/release
          if-no-files-found: error


  integration:
    needs: [product]
    strategy:
      fail-fast: false
      matrix:
        agp-version: ${{ fromJSON(needs.product.outputs.agp-versions) }}
        os: [linux, macos, windows]
        include:
          # Runners must support all the Python versions in setup-python/action.yml: see
          # https://github.com/actions/python-versions/blob/main/versions-manifest.json.
          - os: linux
            runs-on: ubuntu-20.04
          - os: macos
            runs-on: macos-13
          - os: windows
            runs-on: windows-2022

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: smorimoto/tune-github-hosted-runner-network@v1.0.0
      - uses: actions/checkout@v4.1.6

      - uses: ./.github/actions/setup-python
        id: setup-python

      - name: Download Maven repository
        uses: actions/download-artifact@v4.1.7
        with:
          name: maven
          path: maven

      - name: Install Python requirements
        run: |
          ${{ steps.setup-python.outputs.python-default }} -m \
              pip install -r product/gradle-plugin/src/test/integration/requirements.txt

      - uses: ./.github/actions/create-local-properties

      - name: Test
        run: |
          cd product
          export JAVA_HOME=$JAVA_HOME_11_X64
          CHAQUOPY_NO_BUILD=1 ./gradlew testIntegration-${{ matrix.agp-version }}
